config/routes.rb
Rails.application.routes.draw do
  resources :my_coffees

  root 'my_coffees#index'

end

app/models/my_coffee.rb
class MyCoffee < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_coffees_controller.rb
class MyCoffeesController < ApplicationController
  before_action :set_my_coffee, only: [:show, :edit, :update, :destroy]

  # GET /my_coffees
  # GET /my_coffees.json
  def index
    @my_coffees = MyCoffee.all
    respond_to do |format|
      format.html     
      format.xls 
    end

  end

  # GET /my_coffees/1
  # GET /my_coffees/1.json
  def show
  end

  # GET /my_coffees/new
  def new
    @my_coffee = MyCoffee.new
  end

  # GET /my_coffees/1/edit
  def edit
  end

  # POST /my_coffees
  # POST /my_coffees.json
  def create
    @my_coffee = MyCoffee.new(my_coffee_params)

    respond_to do |format|
      if @my_coffee.save
        format.html { redirect_to @my_coffee, notice: 'My coffee was successfully created.' }
        format.json { render :show, status: :created, location: @my_coffee }
      else
        format.html { render :new }
        format.json { render json: @my_coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_coffees/1
  # PATCH/PUT /my_coffees/1.json
  def update
    respond_to do |format|
      if @my_coffee.update(my_coffee_params)
        format.html { redirect_to @my_coffee, notice: 'My coffee was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_coffee }
      else
        format.html { render :edit }
        format.json { render json: @my_coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_coffees/1
  # DELETE /my_coffees/1.json
  def destroy
    @my_coffee.destroy
    respond_to do |format|
      format.html { redirect_to my_coffees_url, notice: 'My coffee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_coffee
      @my_coffee = MyCoffee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_coffee_params
      params.require(:my_coffee).permit(:name, :roast, :ground, :origin, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_coffees_helper.rb
module MyCoffeesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExcelTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_coffees/_form.html.erb
<%= form_for(@my_coffee) do |f| %>
  <% if @my_coffee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_coffee.errors.count, "error") %> prohibited this my_coffee from being saved:</h2>

      <ul>
      <% @my_coffee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :roast %><br>
    <%= f.text_field :roast %>
  </div>
  <div class="field">
    <%= f.label :ground %><br>
    <%= f.check_box :ground %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_coffees/edit.html.erb
<h1>Editing my_coffee</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_coffee %> |
<%= link_to 'Back', my_coffees_path %>

app/views/my_coffees/index.html.erb
<h1>Listing my_coffees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Roast</th>
      <th>Ground</th>
      <th>Origin</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_coffees.each do |my_coffee| %>
      <tr>
        <td><%= my_coffee.name %></td>
        <td><%= my_coffee.roast %></td>
        <td><%= my_coffee.ground %></td>
        <td><%= my_coffee.origin %></td>
        <td><%= my_coffee.notes %></td>
        <td><%= link_to 'Show', my_coffee %></td>
        <td><%= link_to 'Edit', edit_my_coffee_path(my_coffee) %></td>
        <td><%= link_to 'Destroy', my_coffee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My coffee', new_my_coffee_path %>

app/views/my_coffees/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Roast</Data></Cell>
        <Cell><Data ss:Type="String">Ground?</Data></Cell>
        <Cell><Data ss:Type="String">Origin</Data></Cell>
      </Row>
    <% @my_coffees.each do |coffe| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= coffe.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= coffe.roast %></Data></Cell>
        <Cell><Data ss:Type="String"><%= coffe.ground %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= coffe.origin %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/my_coffees/new.html.erb
<h1>New my_coffee</h1>

<%= render 'form' %>

<%= link_to 'Back', my_coffees_path %>

app/views/my_coffees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @my_coffee.name %>
</p>

<p>
  <strong>Roast:</strong>
  <%= @my_coffee.roast %>
</p>

<p>
  <strong>Ground:</strong>
  <%= @my_coffee.ground %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @my_coffee.origin %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @my_coffee.notes %>
</p>

<%= link_to 'Edit', edit_my_coffee_path(@my_coffee) %> |
<%= link_to 'Back', my_coffees_path %>